frase = '   Curso em Vídeo Python   '
print(frase.find('th'))
print('Curso' in frase)
print(len(frase))
print(len(frase.strip()))
print(frase.replace("Python","Androyd"))
print(frase.split())
dividido = frase.split()
print(dividido[3])
print(dividido[3][2])